#############################################################################################################################
# Pilot: Efficient pseudo-random generator!
# After some researches done, it was inferred that there are three main kinds of PRNGs:
#     -Deterministic generators
#     -Generators based on linear recurrences
#     -Cryptographically secure PRNGs
# First kind has some problems because of short periods.
# Third kind is pretty hard to implement. (not that familiar with R!)
# So it was reasonable to choose second type.
# There are three main PRNGs classified in second kind: mersenne twister, xorshift, WELL.
#     +Xorshift has a period of length 2^32 - 1, it means that we can generate almost 4 billion random numbers without loop
#     +Also xorshift was so easy to iplement
#     +And it has the most speed between this kind of PRNGs because of bitwise base
# So xorshift is applied
#
#
# This PRNG function has no parameters:
#
# rgenerator()
# Examples:
# > rgenerator()
# [1] 270369
# > v <- replicate(3, rgenerator())
# > v
# [1]     270369   67634689 2647435461
#
# This implementation is similar to the process of random-number generation in C/C++
# So first, the seed is set with set_seed(seed) function(seed is set to 1 by default)
#
#set_seed(seed)
# Examples:
# > rgenerator()
# [1] 270369
# > set_seed(2018)
# > rgenerator()
# [1] 527741980
# Moreover, there is a function set_seed_to_time() that sets seed to an expression based on time and pid
##############################################################################################################################

library("ggplot2")
SetSeed <- function(seed) {
  x <- seed
  PRNG <- function() {
    if(is.na(x))
      x <<- as.integer((as.double(Sys.time())*1000+Sys.getpid()) %% 2^31)
    x <<- x - (x >= 2^31) * 2^32
    x <<- bitwXor(x, bitwShiftL(x, 13))
    x <<- bitwXor(x, bitwShiftR(x, 17))
    x <<- bitwXor(x, bitwShiftL(x, 5))
    x <<- 2^32 * (x < 0) + x
    return (x)
  }
  return(PRNG)
}

set_seed <- function(seed){
  rgenerator <<- SetSeed(seed)
}

set_seed_to_time <- function(){
  set_seed(as.integer((as.double(Sys.time())*1000+Sys.getpid()) %% 2^31))
}

rgenerator <- SetSeed(1)


#############################################################################################################################
# Function : dugen(left, right)
#
# This function gets two integer numbers as its parameters, left and right, and
# generates a random integer number from [left, right - 1]
#
# Example:
# > v <- replicate(10, dugen(1, 100))
# > v
# [1] 42 59 97 92 94 61 88 22 92 26
#
# This function uses the function rgenerator() in this package to produce random numbers.
#
# Function : duplot(left, right)
#
# This function gets two integer numbers as its parameters, left and right, and
# makes a histogram, using random numbers generated by function dugen(left, right)
##############################################################################################################################

dugen <- function(left, right){
  res <- left + (rgenerator() %% (right - left))
  return (res)
}

duplot <- function(left, right){
  v <- replicate(400000, dugen(left, right))
  df <- data.frame(v)
  plot <- qplot(df$v,
        geom="histogram",
        binwidth = 0.5,
        main = "dugen Histogram",
        xlab = "x")
  return (plot)
}


#############################################################################################################################
# Function : cugen()
#
# This function generates a random integer number with uniform distribution between 0, 1.
#
# Example:
# > v <- replicate(5, cugen())
# > v
# [1] 0.00006295019 0.01574742817 0.61640410242 0.07161863497 0.55848835804
#
# This function uses the function dugen in this package to produce random numbers in specific intervals.
#
# Function : cuplot()
#
# This function makes a histogram, using uniform random numbers generated by function cugen()
##############################################################################################################################

cugen <- function(){
  res <- dugen(0, (2^32)) / (2^32)
  return (res)
}

cuplot <- function(){
  v <- replicate(1000000, cugen())
  df <- data.frame(v)
  plot <- qplot(df$v,
        geom="histogram",
        binwidth = 0.001,
        main = "cugen Histogram",
        xlab = "x")
  return (plot)
}


#############################################################################################################################
# Function : brgen(p)
#
# This function gets a float number p, between 0, 1 as the parameter of a benoulli distribution
# and returns 1 with probability p, and 0 with probability (1-p).
#
# Example:
# > v <- replicate(10, brgen(0.3))
# > v
# [1] 1 1 0 1 0 1 1 1 0 0
#
# This function uses the function cugen in this package.
#
# Function : brplot(p)
#
# This function makes a histogram, using brgen.
##############################################################################################################################

brgen <- function(p){
  res <- as.integer(cugen() <= p)
  return (res)
}

brplot <- function(p){
  v <- replicate(10000, brgen(p))
  df <- data.frame(v)
  plot <- qplot(df$v,
        geom="histogram",
        binwidth = 0.05,
        main = "brgen Histogram",
        xlab = "x")
  return (plot)
}

#############################################################################################################################
# Function : bigen(p, n)
#
# This function acts as a binomial distribution, gets a float number p, and an integer parameter n,
# and counts the number of 1s in n bernoulli trials , done by the function brgen in this package.
#
# Example:
# > v <- replicate(10, bigen(0.3, 10))
# > v
# [1] 6 4 3 5 2 4 5 0 4 3
#
# Function : biplot(p, n)
#
# This function makes a histogram, using bigen.
##############################################################################################################################

bigen <- function(p, n){
  rand <- replicate(n, brgen(p))
  res <- sum(rand[1:n])
  return (res)
}

biplot <- function(p, n){
  v <- replicate(20000, bigen(p, n))
  df <- data.frame(v)
  plot <- qplot(df$v,
        geom="histogram",
        binwidth = 0.5,
        main = "bigen Histogram",
        xlab = "x")
  return (plot)
}

#############################################################################################################################
# Function : gegen(p)
#
# This function acts as a geometric distribution, gets a float number p, and does bernoulli trials,
# and counts them till it comes 1 for the first time.Bernoulli trials are done by the function brgen in this package.
#
# Example:
# > v <- replicate(10, gegen(0.3))
# > v
# [1] 1 1 2 2 1 1 6 1 2 2
#
# Function : geplot(p)
#
# This function makes a histogram, using gegen.
##############################################################################################################################

gegen <- function(p){
  res <- 1
  while(brgen(p) < 1)
    res <- res + 1
  return (res)
}

geplot <- function(p){
  v <- replicate(100000, gegen(p))
  df <- data.frame(v)
  plot <- qplot(df$v,
        geom="histogram",
        binwidth = 0.5,
        main = "gegen Histogram",
        xlab = "x")
  return (plot)
}

#############################################################################################################################
# Function : expgen(landa)
#
# This function acts as an exponential distribution, gets a float number landa, and generates a random number
# by help of a uniform distribution. uniform numbers are produced by the function cugen in this package.
#
# Example:
# > v <- replicate(10, expgen(1))
# > v
# [1] 9.6731668 4.1510782 0.4838525 2.6364000 0.5825215 1.7511501 1.9156210 2.2881163 0.7616178 0.3871972
#
# Function : expplot(landa)
#
# This function makes a histogram, using expgen.
##############################################################################################################################

expgen <- function(landa){
  res <- log(cugen()) / (-landa)
  return (res)
}

expplot <- function(landa){
  v <- replicate(500000, expgen(landa))
  df <- data.frame(v)
  plot <- qplot(df$v,
        geom="histogram",
        binwidth = 0.01,
        main = "expgen Histogram",
        xlab = "x")
  return (plot)
}

#############################################################################################################################
# Function : gagen(landa, k)
#
# This function acts as a gamma distribution, gets a float number landa, and an integer k, and generates a random number
# by adding k exponentially distributed r-numbers. exponential distribution is done by the function expgen in this package.
#
# Example:
# > v <- replicate(5, gagen(1, 3))
# > v
# [1] 14.308098  4.970072  4.965355  1.922696  8.200012
#
# Function : gaplot(landa, k)
#
# This function makes a histogram, using gagen.
##############################################################################################################################

gagen <- function(landa, k){
  res <- 0
  res <- sum(replicate(k, expgen(landa)))
  return (res)
}

gaplot <- function(landa, k){
  v <- replicate(200000, gagen(landa, k))
  df <- data.frame(v)
  plot <- qplot(df$v,
        geom="histogram",
        binwidth = 0.05,
        main = "gagen Histogram",
        xlab = "x")
  return (plot)
}

#############################################################################################################################
# Function : pogen(landa, t)
#
# This function acts as a poisson distribution, gets two float parameters landa, t, and generates a random number
# by counting exponentially distributed r-times in a t-length interval.
# exponential distribution is done by the function expgen in this package.
# the result will be pois(landa*t)
#
# Example:
# > v <- replicate(5, pogen(1, 5))
# > v
# [1] 0 2 3 5 2
#
# Function : poplot(landa, t)
#
# This function makes a histogram, using pogen.
##############################################################################################################################

pogen <- function(landa, t){
  s <- 0
  res <- -1
  while(s - t <= 0){
    s <- s + expgen(landa)
    res <- res + 1
  }
  return (res)
}

poplot <- function(landa, t){
  v <- replicate(100000, pogen(landa, t))
  df <- data.frame(v)
  plot <- qplot(df$v,
        geom="histogram",
        binwidth = 0.5,
        main = "pogen Histogram",
        xlab = "x")
  return (plot)
}

#############################################################################################################################
# Function : nogen(u, s)
#
# This function acts as a normal distribution, gets two float parameters u, s, as mean and variance,
# and generates a random number, using the equivalency pois(landa) = N(landa, landa).
# Poisson distribution is done by the function pogen in this package.
#
# Example:
# > v <- replicate(5, nogen(0, 1))
# > v
# [1] -0.5656854  0.7071068 -0.8485281 -0.9899495  1.5556349
#
# Function : noplot(u, s)
#
# This function makes a histogram, using nogen.
##############################################################################################################################

nogen <- function(u, s){
  rad <- 5 * sqrt(2 * s)
  res <- mean(replicate(50, pogen(1, 1))) * rad - rad + u
  return (res)
}

noplot <- function(u, s){
  v <- replicate(10000, nogen(u, s))
  df <- data.frame(v)
  plot <- qplot(df$v,
        geom="histogram",
        binwidth = 0.05,
        main = "nogen Histogram",
        xlab = "x")
  return (plot)
}
